//ARTS
export const FETCH_ARTS = 'FETCH_ARTS';
export const SEARCH_ARTS = 'SEARCH_ARTS';
export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_FAILED = 'FETCH_FAILED';
export const SORT_ARTS = 'SORT_ARTS';
export const UPDATE_ART = "UPDATE_ART";
export const UPDATE_ART_SUCCESSED = "UPDATE_ART_SUCCESSED";
export const UPDATE_ART_FAILED = "UPDATE_ART_FAILED";
export const ADD_ART = "ADD_ART";
export const ADD_ART_SUCCESSED = "ADD_ART_SUCCESSED";
export const ADD_ART_FAILED = "ADD_ART_FAILED";

//USERS
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCEEDED = 'FETCH_USER_SUCCEEDED';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESSED = "UPDATE_USER_SUCCESSED";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const UPDATE_IMAGE = "UPDATE_IMAGE";
export const UPDATE_IMAGE_SUCCESSED = "UPDATE_IMAGE_SUCCESSED";
export const UPDATE_IMAGE_FAILED = "UPDATE_IMAGE_FAILED"
